### ISSUE TITLE
Dry run

### ISSUE THREAD

**Issue by ilteoood** [sakebook/actions-flutter-pub-publisher#13]
Can you add a new option to run the publish command with the --dry-run (or -n) parameter?

https://dart.dev/tools/pub/cmd/pub-lish

**Comment by ilteoood** [comment]
@sakebook I've made this PR to solve this feature request:
https://github.com/sakebook/actions-flutter-pub-publisher/pull/14/files

**Comment by sakebook** [comment]
close https://github.com/sakebook/actions-flutter-pub-publisher/pull/14
