### ISSUE TITLE
No pubspec.yaml file found error !

### ISSUE THREAD

**Issue by nateshmbhat** [sakebook/actions-flutter-pub-publisher#16]
My repository is 
https://github.com/nateshmbhat/touchable

When the build runs , for some reason it looks like it looks in the example folder rather than the root of the project.

```
Check credentials
OK
Copy credentials
OK
Switching to package directory
Run test
Running "flutter pub get" in workspace...                           2.5s
/github/workspace/example: no pubspec.yaml found
```

**Comment by sakebook** [comment]
If I run the following command locally, does it succeed?

`$ flutter pub publish --dry-run`

**Comment by nateshmbhat** [comment]
Turns out my credentials json secret data had a bad character at the end.

But this plugin failed to give me proper error message. 

I used another plugin called "dart/flutter public" and it gave proper errors.

**Comment by creativecreatorormaybenot** [comment]
This issue can be closed.
