### ISSUE TITLE
How to set the google account credential into secrets?

### ISSUE THREAD

**Issue by JinHoSo** [sakebook/actions-flutter-pub-publisher#8]
Hi, Thanks for this great action.
But I have no idea how to set the google account credential into secrets?

Thanks in advance.

**Comment by sakebook** [comment]
Have a look at this.

https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets

**Comment by JinHoSo** [comment]
@sakebook Thanks but what type of google account credential is used for this action? 
There is a lot of credentials related to google such as google cloud api.

**Comment by leoafarias** [comment]
@JinHoSo `open ~/.pub-cache` you will see a credentials.json there. Just copy the contents into the GitActions secrets and call it a day.
